const socios = {
    
    "08F": { nombre: "GONZALO MORAGA", completado: false },
    "01K": { nombre: "JOSE VILCHES", completado: false },
    "02M": { nombre: "RAFA CORNER", completado: false },
    "33N": { nombre: "GABRIEL ARCO", completado: false },
    "04R": { nombre: "MANUEL GARCÍA \"FALOYA\"", completado: false },
    "05X": { nombre: "RAMÓN MARÍN", completado: false },
    "06L": { nombre: "MARÍA MARTÍN MARTÍNEZ", completado: false },
    "07P": { nombre: "MIGUEL ÁNGEL CAÑO", completado: false },
    "21U": { nombre: "JUAN CARLOS \"CHULO\"", completado: false },
    "58B": { nombre: "JOSÉ ANTONIO ...", completado: false },
    "09H": { nombre: "VÍCTOR MARTÍN MARTÍNEZ", completado: false },
    "10V": { nombre: "JAVI VILCHES", completado: false },
    "11C": { nombre: "MANUEL GIL", completado: false },
    "12N": { nombre: "JUAN \"POLI\"", completado: false },
    "13J": { nombre: "JOSÉ BENÍTEZ", completado: false },
    "14A": { nombre: "CURRO VALVERDE", completado: false },
    "15Y": { nombre: "JORGE ANTOLÍN", completado: false },
    "16E": { nombre: "SERGIO LAGUNA", completado: false },
    "17W": { nombre: "PEDRO MANUEL LAGUNA", completado: false },
    "18Q": { nombre: "MANUEL LUIS LÓPEZ MARTÍN", completado: false },
    "19D": { nombre: "JUAN CARLOS PLAZA", completado: false },
    "20G": { nombre: "PEDRO MARTÍNEZ JAÉN", completado: false },
    "03T": { nombre: "PACO MATEOS", completado: false },
    "22K": { nombre: "JAVITO ALCALDE", completado: false },
    "23M": { nombre: "GONZALO \"TETE\"", completado: false },
    "24T": { nombre: "JOSELINES BENÍTEZ", completado: false },
    "25R": { nombre: "ALBERTO BENÍTEZ", completado: false },
    "26X": { nombre: "GUILLE OLID", completado: false },
    "27L": { nombre: "JORGE SANABRIA", completado: false },
    "28P": { nombre: "ALBERTO FERNÁNDEZ", completado: false },
    "29F": { nombre: "ANTONIO PEREZ", completado: false },
    "30H": { nombre: "ALEX FUENTES", completado: false },
    "31V": { nombre: "JAVI TARDÍO", completado: false },
    "32C": { nombre: "ANDRÉS MORILLO", completado: false },    
    "34J": { nombre: "ÁNGEL PLAZA", completado: false },
    "35A": { nombre: "MANUEL MORATA", completado: false },
    "36Y": { nombre: "JAVIER SIMÓN", completado: false },
    "37E": { nombre: "ANTONIO LUIS \"LUIDSON\"", completado: false },
    "38W": { nombre: "RAFA NOVITA", completado: false },
    "39Q": { nombre: "JUANLU ALDEHUELA", completado: false },
    "40D": { nombre: "DOMINGO PORTILLO", completado: false },
    "41G": { nombre: "ALFONSO BLANCO", completado: false },
    "42U": { nombre: "JAVI CHOMPA", completado: false },
    "43K": { nombre: "EDUARDO", completado: false },
    "44M": { nombre: "ADOLFO MARTÍNEZ", completado: false },
    "45T": { nombre: "MARCOS MORENO", completado: false },
    "46R": { nombre: "GABRIEL NENACO", completado: false },
    "47X": { nombre: "PILAR", completado: false },
    "48L": { nombre: "LÁZARO", completado: false },
    "49P": { nombre: "FRAN MATEOS", completado: false },
    "50F": { nombre: "JUANLU", completado: false },
    "51H": { nombre: "MAYTE GALLARDO", completado: false },
    "52V": { nombre: "ANA RAMOS", completado: false },
    "53C": { nombre: "JUAN CARLOS GARCIA", completado: false },
    "54N": { nombre: "NINO ESTEPA", completado: false },
    "55J": { nombre: "ANTONIO EXPÓSITO", completado: false },
    "56A": { nombre: "ALBERTO EXPÓSITO", completado: false },
    "57A": { nombre: "ADRIÁN", completado: false }
};
